### ISSUE TITLE
FNET-4.6.3 shell wrong command bug

### ISSUE THREAD

**Issue by bwp530** [butok/FNET#2]
in fnet_shell.c
`
                    if(cur_command->name == 0)
                    {
                        fnet_shell_println((fnet_shell_desc_t)shell_if_p, FNET_SHELL_ERR_CMD, argv[0]);
                    }

`
if cur_command is NULL, the program will crash.
so if I input wrong command, the program will crash.

**Comment by AndreyButokNXP** [comment]
Hello, 
the reported is not valid for the latest FNET:
`cur_command->name` is covered by `if(cur_command)` condition.

Soory for the later answer.

**Comment by butok** [comment]
Fixed
