### ISSUE TITLE
Bad link status when used PHY DP83848 in latest FNET version

### ISSUE THREAD

**Issue by zavovi** [butok/FNET#3]
Hi Andrey,
I updated FNET from 4.3.0 to 4.6.3 and I have now issue with link status. The function `_fnet_eth_is_connected` in file `fnet_eth.c` return bad status on my board with PHY DP83848. It was working right, but after update, it is still returning LINK UP, but not connected cable. I tried on lot of boards.

I allowed your hack which is commented for PHY DP8340, but it still returning bad value. It seems, that it read from register bad (I see 0xFFFF in data after called function `_fnet_eth_phy_read(netif, FNET_ETH_MII_REG_SR, &data);` )

Please, could you help me? What did you changed?
Thank you.
Vilem

**Comment by zavovi** [comment]
Hi,
I solved it! I don't know why, but I found one change in fnet_cpu_config.h:

```
#ifndef FNET_CFG_CPU_ETH_PHY_ADDR_DISCOVER
    #define FNET_CFG_CPU_ETH_PHY_ADDR_DISCOVER	(1)
#endif
```

This must be 1 for my using!

Thank you.
Vilem

**Comment by butok** [comment]
Yes, this is for the case when you do not know the address ID of the PHY on your board. So by setting it to 1 the driver is probing PHY addresses one by one. This address is constant for your system.
