### ISSUE TITLE
Virtual routing and forwarding(VRF) integration in FNET stack

### ISSUE THREAD

**Issue by JADAUN-SINGH** [butok/FNET#4]
Hello everyone,
can anyone tell me, How can I implement Virtual Routing and Forwarding(VRF) into FNET stack.
If yes,please share the methods.

**Comment by JADAUN-SINGH** [comment]
Hi @butok ,
I appreciate you if you reply on my comment.

**Comment by butok** [comment]
Virtual Routing and Forwarding(VRF) is not supported by the FNET stack.
Contribution is welcome.
